# modules/pokemon_names.py

pokemon_names = {
    158: {"name": "Totodile", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_158.gif"},
    161: {"name": "Sentret", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_161.gif"},
    21: {"name": "Spearow", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_021.gif"},
    231: {"name": "Phanpy", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_231.gif"},
    187: {"name": "Hoppip", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_187.gif"},
    10: {"name": "Caterpie", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_010.gif"},
    13: {"name": "Weedle", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_013.gif"},
    41: {"name": "Zubat", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_041.gif"},
    60: {"name": "Poliwag", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_060.gif"},
    165: {"name": "Ledyba", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_165.gif"},
    167: {"name": "Spinarak", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_167.gif"},
    69: {"name": "Bellsprout", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_069.gif"},
    74: {"name": "Geodude", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_074.gif"},
    206: {"name": "Dunsparce", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_206.gif"},
    216: {"name": "Teddiursa", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_216.gif"},
    19: {"name": "Rattata", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_019.gif"},
    92: {"name": "Gastly", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_092.gif"},
    16: {"name": "Pidgey", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_016.gif"},
    163: {"name": "Hoothoot", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_163.gif"},
    58: {"name": "Growlithe", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_058.gif"},
    201: {"name": "Unown", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_201.gif"},
    175: {"name": "Togepi", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_175.gif"},
    194: {"name": "Wooper", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_194.gif"},
    72: {"name": "Tentacool", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_072.gif"},
    129: {"name": "Magikarp", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_129.gif"},
    211: {"name": "Qwilfish", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_211.gif"},
    27: {"name": "Sandshrew", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_027.gif"},
    118: {"name": "Goldeen", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_118.gif"},
    79: {"name": "Slowpoke", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_079.gif"},
    23: {"name": "Ekans", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_023.gif"},
    190: {"name": "Aipom", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_190.gif"},
    214: {"name": "Heracross", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_214.gif"},
    204: {"name": "Pineco", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_204.gif"},
    102: {"name": "Exeggcute", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_102.gif"},
    98: {"name": "Krabby", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_098.gif"},
    43: {"name": "Oddish", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_043.gif"},
    46: {"name": "Paras", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_046.gif"},
    48: {"name": "Venonat", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_048.gif"},
    54: {"name": "Psyduck", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_054.gif"},
    39: {"name": "Jigglypuff", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_039.gif"},
    174: {"name": "Igglybuff", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_174.gif"},
    63: {"name": "Abra", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_063.gif"},
    96: {"name": "Drowzee", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_096.gif"},
    132: {"name": "Ditto", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_132.gif"},
    236: {"name": "Tyrogue", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_236.gif"},
    66: {"name": "Machop", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_066.gif"},
    104: {"name": "Cubone", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_104.gif"},
    202: {"name": "Wobbuffet", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_202.gif"},
    209: {"name": "Snubbull", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_209.gif"},
    193: {"name": "Yanma", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_193.gif"},
    29: {"name": "Nidoran ♀", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_029.gif"},
    32: {"name": "Nidoran ♂", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_032.gif"},
    191: {"name": "Sunkern", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_191.gif"},
    123: {"name": "Scyther", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_123.gif"},
    127: {"name": "Pinsir", "gif": "https://www.pokencyclopedia.info/sprites/gen2/ani_crystal_shiny/ani_c-S_127.gif"},
}
